import { Professional, ProfessionalCategory } from '../types';

export const sampleProfessionals: Professional[] = [
  {
    id: "1",
    email: "maya.johnson@example.com",
    name: "Dr. Maya Johnson",
    title: "Family Medicine Physician",
    category: ProfessionalCategory.HEALTH,
    bio: "Board-certified family medicine physician with 15 years of experience. Specializing in preventive care and chronic disease management.",
    credentials: "MD, Board Certified in Family Medicine",
    hourly_rate: 150,
    rating: 4.9,
    reviews_count: 127,
    verified: true,
    image_url: undefined,
    phone: "(555) 123-4567",
    created_at: new Date().toISOString()
  },
  {
    id: "2",
    email: "marcus.williams@example.com",
    name: "Attorney Marcus Williams",
    title: "Civil Rights Attorney",
    category: ProfessionalCategory.LEGAL,
    bio: "Experienced civil rights attorney dedicated to fighting for justice and equality. Specializing in employment discrimination and police misconduct cases.",
    credentials: "JD, Licensed in NY, NJ, and PA",
    hourly_rate: 250,
    rating: 5.0,
    reviews_count: 84,
    verified: true,
    image_url: undefined,
    phone: "(555) 234-5678",
    created_at: new Date().toISOString()
  },
  {
    id: "3",
    email: "jasmine.carter@example.com",
    name: "Jasmine Carter, CPA",
    title: "Certified Public Accountant",
    category: ProfessionalCategory.FINANCE,
    bio: "CPA specializing in tax preparation and financial planning for small businesses and individuals. Helping clients build generational wealth.",
    credentials: "CPA, MBA in Finance",
    hourly_rate: 125,
    rating: 4.8,
    reviews_count: 156,
    verified: true,
    image_url: undefined,
    phone: "(555) 345-6789",
    created_at: new Date().toISOString()
  },
  {
    id: "4",
    email: "terrell.brown@example.com",
    name: "Coach Terrell Brown",
    title: "Life & Business Coach",
    category: ProfessionalCategory.COACHING,
    bio: "Empowering entrepreneurs and professionals to reach their full potential. 10+ years coaching experience with proven results.",
    credentials: "ICF Certified Coach, MBA",
    hourly_rate: 175,
    rating: 4.7,
    reviews_count: 92,
    verified: true,
    image_url: undefined,
    phone: "(555) 456-7890",
    created_at: new Date().toISOString()
  },
  {
    id: "5",
    email: "aisha.thompson@example.com",
    name: "Dr. Aisha Thompson",
    title: "Clinical Psychologist",
    category: ProfessionalCategory.HEALTH,
    bio: "Licensed clinical psychologist specializing in trauma, anxiety, and depression. Culturally-sensitive therapy for the Black community.",
    credentials: "PhD in Clinical Psychology, Licensed Psychologist",
    hourly_rate: 180,
    rating: 5.0,
    reviews_count: 203,
    verified: true,
    image_url: undefined,
    phone: "(555) 567-8901",
    created_at: new Date().toISOString()
  },
  {
    id: "6",
    email: "kwame.davis@example.com",
    name: "Professor Kwame Davis",
    title: "STEM Education Consultant",
    category: ProfessionalCategory.EDUCATION,
    bio: "Former university professor now consulting on STEM education programs. Passionate about increasing Black representation in STEM fields.",
    credentials: "PhD in Computer Science, 20+ years teaching experience",
    hourly_rate: 200,
    rating: 4.9,
    reviews_count: 67,
    verified: true,
    image_url: undefined,
    phone: "(555) 678-9012",
    created_at: new Date().toISOString()
  }
];
